name: multi-branch

on:
  push:
    branches:
      - prod
      - dev
      - qa
      - test

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Prod message
      run: |
        echo "doing the cahnges in live prod"
