name: multi-branch

on:
  push:
    branches:
      - prod
      - dev
      - qa
      - test

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Execute Branch Logic
      run: |
          case "${{ github.ref_name }}" in
            "prod")
              echo " Deploying to PRODUCTION"
              ;;
            "qa")
              echo " Deploying to QA"
              ;;
            "test")
              echo " Deploying to TEST"
              ;;
            "dev")
              echo " Deploying to DEV"
              ;;
          esac
